### ISSUE TITLE
Ensure that repository removal functionality works and is hooked up to ferryctl

### ISSUE THREAD

**Issue by ermo** [getsolus/ferryd#34]
`DeleteRepo` pops up one time too many in a `rg DeleteRepo` search to be "not yet implemented" as one comment says in `ferryd/core/repo.go`.

We need this functionality for easy testing of the epoch bump where we need to be able to do quick successive cycles of create/index/remove `<the epoch testing repo>`.

**Comment by livingsilver94** [comment]
Are you sure that's not a stale comment? This sequence of command works:

```shell
mkdir bin/myRepoBase
./bin/ferryd -d bin/myRepoBase -s ./ferryd.sock &
./bin/ferryctl -s ./ferryd.sock create-repo testing
# bin/myRepoBase/repo/testing has content
./bin/ferryctl -s ./ferryd.sock remove remove testing
# bin/myRepoBase/repo/testing is now empty
```

**Comment by livingsilver94** [comment]
Ok so, the core API is working according to my test, plus so is the ferryctl invocation. The HTTP API remains to be tested then.

**Comment by ermo** [comment]
> Ok so, the core API is working according to my test, plus so is the ferryctl invocation. The HTTP API remains to be tested then.

Any chance we could rename the command-line invocation to `remove-repo` perhaps...?

**Comment by livingsilver94** [comment]
Shouldn't be hard at all!

**Comment by livingsilver94** [comment]
This works: `curl --unix-socket /path/to/ferryd.sock http://localhost/api/v1/remove/repo/testing`

So yeah, it's definitely a stale comment. Gonna implement what you requested.
